# Generated by Django 3.0.5 on 2020-05-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200504_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDoc',
        ),
    ]
