# Generated by Django 3.0.5 on 2020-05-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postimage_post_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post_image_name',
        ),
    ]
