# Generated by Django 3.0.5 on 2020-05-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
