# Generated by Django 3.0.5 on 2020-05-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_paragraph_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_paragraph', to='blog.Post'),
        ),
    ]
